name: Flyyv Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}

      - name: Add Dokku host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H flyyv-backend >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        run: |
          git remote add dokku dokku@flyyv-backend:flyyv || true
          git push dokku main --force
