name: Deploy to Dokku

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 165.227.185.157 >> ~/.ssh/known_hosts

      - name: Trigger Dokku git sync
        env:
          DOKKU_APP: flyyv
          GIT_REPO: https://github.com/nugecko/flyyv-backend.git
        run: |
          ssh root@165.227.185.157 "dokku git:sync $DOKKU_APP $GIT_REPO main"
